version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: Git restore cache
          keys:
            - source-v3-{{ .Branch }}-{{ .Revision }}
            - source-v3-{{ .Branch }}-
      - run: 
          name: Fetch git tags 
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects 
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v3-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install:
    description: "Install node modules"
    steps:
      - restore_cache:
          name: Restoring node_modules
          keys:
            - source-v3-modules-{{ checksum "package-lock.json" }}
            - source-v3-modules
      - run:
          name: npm install
          command: npm install
      - save_cache:
          name: Save node_module
          key: source-v3-modules-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  test:
    description: Test App
    steps:
      - run:
          name: Testing App
          command: npm run test
  build:
    description: Build App
    steps:
      - run:
          name: Building App
          no_output_timeout: 30m
          command: npm run build-travis
  deploy:
    description: "Deploy"
    parameters:
      target_branch:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >> $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > version
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci-build@bianry.com "
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "01:67:4a:6d:26:9c:70:c4:1a:60:91:88:d9:dd:f0:83"
      - run:
          name: Deploy docs to gh-pages branch
          command: node ./node_modules/gh-pages/bin/gh-pages --dist '.' --src '{index.html,version,dist/*}' --branch << parameters.target_branch >> --message '[skip ci]'
  docker_build_push:
    description: "Build Docker image"
    parameters:
      docker_image_tag:
        type: string
        default: "beta-latest"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static-charts:${CIRCLE_TAG} -t ${DOCKHUB_ORGANISATION}/binary-static-charts:<< parameters.docker_image_tag >> .
      - run: 
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static-charts
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "charts-binary-com-beta"
    steps:
      - k8s/install-kubectl
      - run: 
          name: Deploying to k8s cluster for service binary-charts
          command: |
            for SERVER_ID in {1..5}
            do
              KUBE_SERVER_REF="KUBE_SERVER_$SERVER_ID"
              SERVICEACCOUNT_TOKEN_REF="SERVICEACCOUNT_TOKEN_$SERVER_ID"
              CA_CRT_REF="CA_CRT_$SERVER_ID"
              if [ ! -z "${!KUBE_SERVER_REF}" ]
              then
                echo "Deploying to cluster $SERVER_ID"
                CA_CRT="${!CA_CRT_REF}"
                KUBE_SERVER="${!KUBE_SERVER_REF}"
                SERVICEACCOUNT_TOKEN="${!SERVICEACCOUNT_TOKEN_REF}"
                echo $CA_CRT | base64 --decode > ca.crt
                kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/<< parameters.k8s_svc_name >> << parameters.k8s_svc_name >>=${DOCKHUB_ORGANISATION}/binary-static-charts:${CIRCLE_TAG}
              fi
            done
  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for Smartchart with version *$(cat version)*"
          success_message: "Release succeeded for Smartchart with version *$(cat version)*"
          webhook: ${SLACK_WEBHOOK}
jobs:
  test:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - test
  release_beta:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - test
      - build
      - deploy:
          target_branch: "staging"
      - notify_slack
  release_production:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - test
      - build
      - deploy:
          target_branch: "production"
      - notify_slack
  release_aws_production:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - test
      - build
      - docker_build_push:
          docker_image_tag: latest
      - k8s_deploy:
          k8s_svc_name: "charts-binary-com"

workflows:
  test:
    jobs:
      - test:
          filters:
             branches:
               ignore: /^master$/
  release:
    jobs:
      - release_beta:
          filters:
            branches:
              only: /^master$/
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
      - release_aws_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
